version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: DockerFile  # Changed to match your actual filename
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
    restart: always
    container_name: react-app-prod
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:5001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"